name: gpt_python_cli
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - arrow-cpp=11.0.0
  - async-timeout=4.0.2
  - attrs=23.1.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - blas=1.0
  - boost-cpp=1.65.1
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.5.7
  - cachetools=5.3.0
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - colorama=0.4.6
  - cryptography=38.0.4
  - dataclasses=0.8
  - dataclasses-json=0.5.7
  - datasets=2.12.0
  - dill=0.3.6
  - et_xmlfile=1.1.0
  - filelock=3.12.0
  - frozenlist=1.3.3
  - fsspec=2023.5.0
  - future=0.18.3
  - gflags=2.2.2
  - glog=0.5.0
  - gptcache=0.1.29.1
  - greenlet=2.0.1
  - grpc-cpp=1.46.1
  - huggingface_hub=0.15.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - intel-openmp=2021.4.0
  - jmespath=0.10.0
  - joblib=1.2.0
  - keyutils=1.6.1
  - krb5=1.19.3
  - langchain=0.0.153
  - ld_impl_linux-64=2.38
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.87.0
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.46.0
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libuuid=1.41.5
  - lz4-c=1.9.4
  - marshmallow=3.19.0
  - marshmallow-enum=1.5.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - multiprocess=0.70.14
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openai=0.25.0
  - openapi-schema-pydantic=1.2.4
  - openpyxl=3.0.9
  - openssl=1.1.1t
  - orc=1.7.4
  - packaging=23.1
  - pandas=1.5.3
  - pandas-stubs=2.0.1.230501
  - pip=23.0.1
  - pyarrow=11.0.0
  - pycparser=2.21
  - pydantic=1.10.2
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python-xxhash=3.0.0
  - python_abi=3.10
  - pytorch=1.13.1
  - pytz=2023.3
  - pyyaml=6.0
  - re2=2022.04.01
  - readline=8.2
  - regex=2022.7.9
  - requests=2.31.0
  - responses=0.18.0
  - sacremoses=0.0.53
  - setuptools=67.8.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlalchemy=1.4.39
  - sqlite=3.41.2
  - stringcase=1.2.0
  - tenacity=8.2.2
  - tk=8.6.12
  - tokenizers=0.11.4
  - tqdm=4.65.0
  - transformers=4.29.2
  - types-pytz=2023.3.0.0
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - typing_inspect=0.9.0
  - tzdata=2023c
  - urllib3=2.0.2
  - utf8proc=2.6.1
  - wheel=0.38.4
  - xxhash=0.8.0
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.5
